### ISSUE TITLE
Exception while invoking method 'logVisit' Error: Did not check() all arguments during call to 'logVisit'

### ISSUE THREAD

**Issue by tcastelli** [meteorbigdata/visit-tracker#4]
Is it possible to update the package with a check of all the parameters, if not caring about proper value types a call to check(arguments, [Match.Any]) could be enough. (parameter check is encouraged though)

**Comment by smothers** [comment]
+1

**Comment by udiedrichsen** [comment]
Yeah, would be great. I also get this exception:

I20150517-07:45:04.993(2)? Exception while invoking method 'headersToken' Error: Did not check() all arguments during call to 'headersToken'
I20150517-07:45:04.993(2)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150517-07:45:04.993(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150517-07:45:04.993(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150517-07:45:04.993(2)?     at _.extend.protocol_handlers.method.exception (packages/ddp/livedata_server.js:648:1)
I20150517-07:45:04.993(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150517-07:45:04.993(2)?     at packages/ddp/livedata_server.js:647:1
I20150517-07:45:04.994(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150517-07:45:04.994(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150517-07:45:04.994(2)?     at _.extend.processMessage.processNext (packages/ddp/livedata_server.js:546:1)
I20150517-07:45:05.540(2)? Exception while invoking method 'logVisit' Error: Did not check() all arguments during call to 'logVisit'
I20150517-07:45:05.540(2)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150517-07:45:05.540(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150517-07:45:05.540(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150517-07:45:05.540(2)?     at _.extend.protocol_handlers.method.exception (packages/ddp/livedata_server.js:648:1)
I20150517-07:45:05.540(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150517-07:45:05.540(2)?     at packages/ddp/livedata_server.js:647:1
I20150517-07:45:05.540(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150517-07:45:05.540(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150517-07:45:05.541(2)?     at _.extend.processMessage.processNext (packages/ddp/livedata_server.js:546:1)
